[package]
name = "descriptor-wallet"
version = "0.5.0-alpha.5"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Library for building descriptor-based bitcoin wallets"
repository = "https://github.com/rust-bitcoin/descriptor-wallet"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "miniscript"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt"]

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = "3.8.2"
descriptors = { version = "0.5.0-alpha.2", path = "./descriptors", optional = true }
bitcoin_scripts = { version = "0.5.0-alpha.3", path = "./scripts" }
bitcoin_hd = { version = "0.5.0-alpha.3", path = "./hd" }
psbt = { version = "0.5.0-alpha.2", path = "./psbt" }
slip132 = { version = "0.5.0-beta.1", path = "./slip132", features = ["strict_encoding"] }
commit_verify = "0.5.4"
strict_encoding = { version = "1.6.1", features = ["bitcoin", "miniscript", "derive"] } # TODO #5: Make strict encoding optional and decrease MSRV
bitcoin = "0.27"
miniscript = { version = "6", features = ["compiler"] }
electrum-client = { version = "0.8", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
chrono = "0.4"

[dev-dependencies]
bitcoin = { version = "0.27", features = ["rand"] }

[features]
default = []
all = ["keygen", "serde", "electrum"]
keygen = ["bitcoin/rand", "commit_verify/rand", "amplify/rand"]
electrum = ["electrum-client"]
serde = ["serde_crate", "serde_with", "amplify/serde",
         "bitcoin/use-serde", "bitcoin_scripts/serde", "bitcoin_hd/serde", "miniscript/serde", "slip132/serde"]

[workspace]
members = [".", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt"]
default-members = ["."]
exclude = ["dep_test"]
