[package]
name = "descriptor-wallet"
version = "0.9.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Libraries and command line tool for building descriptor-based bitcoin wallets"
repository = "https://github.com/BP-WG/descriptor-wallet"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "miniscript"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt"]

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "btc-hot"
required-features = ["hot", "cli"]

[[bin]]
name = "btc-cold"
required-features = ["cli"]

[dependencies]
amplify = "3.13.0"
bitcoin = "0.29.2"
bitcoin_scripts = "0.9.0"
bitcoin_blockchain = "0.9.0"
bitcoin_hd = { version = "0.9.0", path = "./hd" }
bitcoin_onchain = { version = "0.9.0", path = "./onchain" }
bitcoin_hwi = { version = "0.3.0", optional = true }
descriptors = { version = "0.9.0", path = "./descriptors", optional = true, default-features = false }
psbt = { version = "0.9.0", path = "./psbt", default-features = false }
slip132 = { version = "0.9.0", path = "./slip132" }
miniscript_crate = { package = "miniscript", version = "9.0.0", optional = true }
electrum-client = { version = "0.13.0", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.14", features = ["hex"], optional = true }
serde_yaml = { version = "0.9", optional = true }
chrono = "0.4"
clap = { version = "~3.2.23", optional = true, features = ["derive"] }
bip39 = { version = "1.0.1", optional = true }
aes = { version = "0.7.5", optional = true }
rpassword = { version = "5.0.1", optional = true }
colored = { version = "2", optional = true }

[dev-dependencies]
bitcoin = { version = "0.29.2", features = ["rand"] }

[features]
default = []
all = [
    "miniscript",
    "electrum",
    "keygen",
    "construct",
    "sign",
    "hwi",
    "hot",
    "cli",
    "serde",
]
miniscript = [
    "bitcoin_hd/miniscript",
    "bitcoin_onchain/miniscript_descriptors",
    "descriptors/miniscript",
    "psbt/miniscript",
]
electrum = [
    "electrum-client",
    "bitcoin_onchain/electrum"
]
sign = ["psbt/sign"]
construct = ["psbt/construct"]
hot = [
    "keygen",
    "bip39",
    "aes",
    "rpassword",
    "sign"
]
hwi = ["bitcoin_hwi"]
cli = [
    "hwi",
    "electrum",
    "construct",
    "miniscript",
    "miniscript_crate",
    "serde",
    "colored",
    "clap",
    "serde_yaml",
    "bitcoin/base64"
]
keygen = ["bitcoin/rand", "amplify/rand", "descriptors/rand"]
serde = [
    "slip132/serde",
    "bitcoin_onchain/serde",
    "bitcoin_hd/serde",
    "psbt/serde",
    "descriptors/serde"
]

[workspace]
members = [".", "slip132", "descriptors", "hd", "psbt", "onchain"]
default-members = ["."]
exclude = ["contrib", "libbitcoin"]
