[package]
name = "descriptor-wallet"
version = "0.6.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Libraries and command line tool for building descriptor-based bitcoin wallets"
repository = "https://github.com/rust-bitcoin/descriptor-wallet"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "wallet", "cryptocurrency", "descriptor", "miniscript"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "contrib", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt"]

[lib]
name = "wallet"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "btc-hot"
required-features = ["keygen", "bip39", "aes", "rpassword", "cli"]

[[bin]]
name = "btc-cold"
required-features = ["electrum", "cli"]

[dependencies]
amplify = "3.9.1"
descriptors = { version = "0.6.0", path = "./descriptors", optional = true }
bitcoin_scripts = { version = "0.6.0", path = "./scripts" }
bitcoin_hd = { version = "0.6.0", path = "./hd" }
bitcoin_onchain = { version = "0.6.0", path = "./onchain" }
psbt = { version = "0.6.0", path = "./psbt" }
slip132 = { version = "0.6.0", path = "./slip132", features = ["strict_encoding"] }
commit_verify = { version = "0.6.0", git = "https://github.com/LNP-BP/client_side_validation", branch = "develop" }
# TODO #5: Make strict encoding optional
strict_encoding = { version = "1.8.0", git = "https://github.com/LNP-BP/client_side_validation", branch = "develop", features = ["bitcoin", "miniscript", "derive"] }
bitcoin = { version = "0.28", git = "https://github.com/LNP-BP/rust-bitcoin", branch = "taproot/all" }
miniscript = { version = "7", git = "https://github.com/LNP-BP/rust-miniscript", branch = "taproot", features = ["compiler"] }
electrum-client = { version = "0.9", git = "https://github.com/LNP-BP/rust-electrum-client", branch = "taproot", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
serde_yaml = { version = "0.8.21", optional = true }
chrono = "0.4"
clap = { version = "3.0.0-beta.5", optional = true }
bip39 = { version = "1.0.1", optional = true }
aes = { version = "0.7.5", optional = true }
rpassword = { version = "5.0.1", optional = true }
colored = { version = "2", optional = true }

[dev-dependencies]
bitcoin = { version = "0.28", git = "https://github.com/LNP-BP/rust-bitcoin", branch = "taproot/all", features = ["rand"] }

[features]
default = []
all = ["keygen", "serde", "electrum"]
cli = ["serde", "colored", "clap", "serde_yaml"]
electrum = ["electrum-client", "bitcoin_onchain/electrum"]
keygen = ["bitcoin/rand", "commit_verify/rand", "amplify/rand", "descriptors/rand", "psbt/sign"]
serde = ["serde_crate", "serde_with", "amplify/serde",
         "bitcoin/use-serde", "bitcoin_scripts/serde", "bitcoin_hd/serde", "miniscript/serde", "slip132/serde"]

[workspace]
members = [".", "slip132", "libbitcoin", "descriptors", "scripts", "hd", "psbt", "onchain"]
default-members = ["."]
exclude = ["dep_test"]
